---
title: "Data 622 Homework 2"
author: "Sung Lee"
date: '2022-03-24'
output: 
  html_document:
    code_folding: show
    df_print: paged
    toc: true
    toc_float: true
    toc_collapsed: true
    smooth_scroll: false
    toc_depth: 3
number_sections: true
theme: paper
---

# Assignment  
Based on the latest topics presented, bring a dataset of your choice and create a Decision Tree where you can solve a classification or regression problem and predict the outcome of a particular feature or detail of the data used. Switch variables to generate 2 decision trees and compare the results. Create a random forest for regression and analyze the results. Based on real cases where desicion trees went wrong, and 'the bad & ugly' aspects of decision trees [https://decizone.com/blog/the-good-the-bad-the-ugly-of-using-decision-trees](https://decizone.com/blog/the-good-the-bad-the-ugly-of-using-decision-trees), how can you change this perception when using the decision tree you created to solve a real problem?
Format: document with screen captures & analysis.  


# Data  
For this assignment, I used the "Flavors of Cacao" dataset from this [https://www.kaggle.com/datasets/techiesid01/flavours-of-cacao?resource=download]( Kaggle website). With this dataset, I will create a decision tree that will solve a regression problem. The dataset will be split in a training and testing partitions.  

```{r}
library(tidymodels)

chocolate <- read_csv('')


```
